version: '2'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=ecto://postgres:postgres@postgres/hexweb_dev
    command: sh -c "mix ecto.migrate HexWeb.Repo && mix phoenix.server"
  postgres:
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=hexweb_dev
