version: '2'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
